name: Coveralls
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:

    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Installing dependencies
      run: npm install
      working-directory: ./backend
    - name: Generating coverage information
      run: npm run coverage
      working-directory: ./backend
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
